SENDGRID:
  EMAIL_APIKEY: sendgridapikey
  EMAIL_FROM: verifiedemail@example.com
  EMAIL_TO: 
    - emailto1@example.com
    - emailto2@example.com
  EMAIL_CC:
    - emailcc1@example.com
    - emailcc2@example.com
